title: Gino's Site! 
tagline: Computer architecture, security, memory, uarch predictors, and random junk 

remote_theme: pages-themes/midnight@v0.2.0 #pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme

url: "https://GinoAC.github.io"
baseurl: ""
#remote_theme: pages-themes/slate@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
excerpt_separator: "<!--more-->"
